package com.sunny.euler._1_to_10

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

 */


fun main() {
    print(euler2(4_000_000))
}

fun euler2(limit : Int): Int    {

    var sum = 0
    var prev = 1
    var current = 1;
    while (current < limit) {
        val temp = prev;
        prev = current;
        current += temp;

        if (current % 2 == 0)   {
            sum += current
        }
    }

    return sum;
}


